### PR TITLE
Apple mobility data

### PR DESCRIPTION
**Pull request by mgithub40**
Adding apple mobility data to be merged

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @mgithub40 , thank you for the pull-request. 
Could you please complete the metadata file before we can merge the pull-merge?
Many thanks,
Lucie

**Comment by mgithub40** [comment]
Hi Lucie, 

Metadata file has been updated. Can you please merge the data.

**Comment by mgithub40** [comment]
Hi Lucie,

Adding case counts for India

**Comment by mgithub40** [comment]
Hi Lucie,

Adding vaccination data

**Comment by LucieContamin** [comment]
Hi @mgithub40,

Thank you very much for the pull-request and all the updates. However, we will be transitioning this GitHub repository to an online repository on the MIDAS website in the next months. We will not be accepting GitHub Pull requests or other contributions to this repository. If you'd like to point us to datasets, software, or other useful information, please post an issue and we'll aim to include the resource in the forthcoming MIDAS data portal. We will keep the information include in the pull-request for the MIDAS data portal.

Many thanks,
Lucie

**Pull request closed without merging**
